-- Table: prebatch_items
-- Backup: 2026-03-11T18:43:46.935866

CREATE TABLE `prebatch_items` (
  `id` int NOT NULL AUTO_INCREMENT,
  `batch_db_id` int NOT NULL,
  `plan_id` varchar(50) DEFAULT NULL,
  `batch_id` varchar(100) DEFAULT NULL,
  `re_code` varchar(50) DEFAULT NULL,
  `ingredient_name` varchar(200) DEFAULT NULL,
  `required_volume` float DEFAULT NULL,
  `wh` varchar(50) DEFAULT 'Mix',
  `status` int DEFAULT '0',
  `batch_record_id` varchar(100) DEFAULT NULL,
  `net_volume` float DEFAULT NULL,
  `package_no` int DEFAULT '1',
  `total_packages` int DEFAULT '1',
  `intake_lot_id` varchar(50) DEFAULT NULL,
  `mat_sap_code` varchar(50) DEFAULT NULL,
  `prebatch_id` varchar(100) DEFAULT NULL,
  `recode_batch_id` varchar(50) DEFAULT NULL,
  `total_volume` float DEFAULT NULL,
  `total_request_volume` float DEFAULT NULL,
  `recheck_status` int DEFAULT '0',
  `recheck_at` datetime DEFAULT NULL,
  `recheck_by` varchar(100) DEFAULT NULL,
  `packing_status` int DEFAULT '0',
  `packed_at` timestamp NULL DEFAULT NULL,
  `packed_by` varchar(50) DEFAULT NULL,
  `weighed_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_pi_plan` (`plan_id`),
  KEY `idx_pi_batch` (`batch_id`),
  KEY `idx_pi_recode` (`re_code`),
  KEY `idx_pi_batchdb` (`batch_db_id`),
  KEY `idx_pi_status` (`status`),
  KEY `idx_pi_packing` (`packing_status`),
  KEY `idx_pi_lot` (`intake_lot_id`),
  KEY `idx_pi_sap` (`mat_sap_code`),
  KEY `idx_pi_brid` (`batch_record_id`),
  CONSTRAINT `prebatch_items_ibfk_1` FOREIGN KEY (`batch_db_id`) REFERENCES `production_batches` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1482 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
