-- Table: sku_steps
-- Exported: 2026-03-11T18:36:02.869425

CREATE TABLE `sku_steps` (
  `id` int NOT NULL AUTO_INCREMENT,
  `sku_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `phase_number` varchar(20) DEFAULT NULL,
  `phase_id` varchar(50) DEFAULT NULL,
  `master_step` int NOT NULL,
  `sub_step` int NOT NULL,
  `destination` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `re_code` varchar(50) DEFAULT NULL,
  `action_code` varchar(50) DEFAULT NULL,
  `action_description` varchar(100) NOT NULL,
  `setup_step` varchar(100) DEFAULT NULL,
  `require` float DEFAULT NULL,
  `low_tol` float DEFAULT '0.001',
  `high_tol` float DEFAULT NULL,
  `agitator_rpm` float DEFAULT NULL,
  `high_shear_rpm` float DEFAULT NULL,
  `temperature` float DEFAULT NULL,
  `ph` float DEFAULT '7',
  `step_time` int DEFAULT NULL,
  `step_timer_control` int DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `qc_temperature` tinyint(1) DEFAULT '0',
  `brix` float DEFAULT NULL,
  `qc_ph` tinyint(1) DEFAULT NULL,
  `qc_brix` tinyint(1) DEFAULT NULL,
  `uom` varchar(20) DEFAULT NULL,
  `temp_low` float DEFAULT NULL,
  `temp_high` float DEFAULT NULL,
  `step_condition` varchar(100) DEFAULT NULL,
  `qc_temp` tinyint(1) DEFAULT '0',
  `record_steam_pressure` tinyint(1) DEFAULT '0',
  `record_ctw` tinyint(1) DEFAULT '0',
  `operation_brix_record` tinyint(1) DEFAULT '0',
  `operation_ph_record` tinyint(1) DEFAULT '0',
  `brix_sp` varchar(50) DEFAULT NULL,
  `ph_sp` varchar(50) DEFAULT NULL,
  `action` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `ix_sku_steps_id` (`id`),
  KEY `ix_sku_steps_sku_id` (`sku_id`)
) ENGINE=InnoDB AUTO_INCREMENT=675 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
